version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data: